controllers/GalleryController.php
<?php
/**
 * Created by PhpStorm.
 * User: bw
 * Date: 20.02.2015
 * Time: 14:02
 */

namespace app\controllers;

use app\models\ImagesAlbum;
use Yii;
use yii\web\Controller;


class GalleryController extends Controller
{
    public function actionIndex()
    {
        $albums = ImagesAlbum::find()->all();
        return $this->render('index', ['albums' => $albums]);
    }

    public function actionView($id)
    {
        $album = ImagesAlbum::find()->where(['id_album' => $id])->with('images')->one();
        return $this->render('view', ['album' => $album]);
    }

}

views/gallery/index.php
<?php
/**
 * Created by PhpStorm.
 * User: bw
 * Date: 13.02.15
 * Time: 18:02
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = Yii::t('app', 'Gallery');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <ul>
        <?php foreach ($albums as $item): ?>
            <li>
                <?= Html::a($item->name,Url::to(['gallery/view', 'id' => $item->id_album])) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

views/gallery/view.php
<?php
/**
 * Created by PhpStorm.
 * User: bw
 * Date: 13.02.15
 * Time: 18:02
 */
use yii\helpers\Html;

$this->title = $album->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Gallery'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-view">

    <h1><?= Html::encode($album->name) ?></h1>


    <ul>
        <?php foreach ($album->images as $item): ?>
            <li>
                <?= Html::img($item->link, ['width' => '50%']) ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>